### ISSUE TITLE
Restrict auto generation to a given namespace

### ISSUE THREAD

**Issue by greg0ire** [Elao/ElaoFormTranslationBundle#10]
I'd like to use the feature on some forms that are under a given namespace, but not on all forms. I use Sonata for the backend part of my website and I don't want Elao to interfere with it. So this would change the possible values for the `auto_generate` settings : it could be a boolean, a namespace or even an array of namespaces.

**Comment by benji07** [comment]
Spring cleaning, If this issue is still relevant, please reopen-it.
