### ISSUE TITLE
Is it possible to change the translation domain?

### ISSUE THREAD

**Issue by xinjia95** [Elao/ElaoFormTranslationBundle#16]
Hi,

I'm interested know if it's possible to change the translation domain. For example, change messages.en.yml to forms.en.yml to have a better organizing translations.

Thanks.

**Comment by Tom32i** [comment]
Hi,

This bundle's only in charge of generating logical keys for different parts of the form (like labels).
It doesn't handle translation. The translation is done when rendering the form template.

So you can change the translation domain just like you would do in any Symfony project:

__In your form configuration:__

    /**
     * {@inheritdoc}
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults([
            'translation_domain' => 'foo',
        ]);
    }

__Or directly in your templates:__

    {{ form(form, { translation_domain: 'foo' }) }}

Did this answered you question?

**Comment by xinjia95** [comment]
Hi,

Yes, your answer is exactly that I need, I didn't remember this solution.

Thanks.

**Comment by Tom32i** [comment]
:+1:
