### ISSUE TITLE
Add an optional formater on form fields in key generation (Make field names undercored)

### ISSUE THREAD

**Issue by bigfoot90** [Elao/ElaoFormTranslationBundle#17]
Add an option to allow underscore-ize field names

**Comment by bigfoot90** [comment]
@Tom32i ping

**Comment by benji07** [comment]
@bigfoot90 may be you can create a pull request ? Instead of just asking for new feature

**Comment by bigfoot90** [comment]
Sure, just want to be sure you want that feature

**Comment by benji07** [comment]
why not, if we can disable it

**Comment by Tom32i** [comment]
Hey @bigfoot90 sorry for my silence :)

What exactly do you mean by "underscore-ize field names" ?

**Comment by bigfoot90** [comment]
suppose you have ```$builder->add('myFieldName');``` in form builder,
the translation id will be ```form.my_form.children.my_field_name.label```

**Comment by Tom32i** [comment]
Oh all right, that could prove useful.

I'm thinking of implementing it that way:
For now the FormTreeNode gets its name from the field name: `new FormTreeNode($view->vars['name'], ...)`. We could add a Transformer that process that value before passing it to the FormTreeNode.

See: https://github.com/Elao/ElaoFormTranslationBundle/blob/master/Builders/FormTreeBuilder.php#L75

**Comment by bigfoot90** [comment]
@Tom32i I was thinking adding a paramiter in bundle configuration only, do you have need to set the label transformer for each field?

**Comment by benji07** [comment]
Spring cleaning, If this issue is still relevant, please reopen-it.
