### ISSUE TITLE
no translation files

### ISSUE THREAD

**Issue by elvis2** [Elao/ElaoFormTranslationBundle#18]
Hello,

I followed the instructions and used the Global option:

elao_form_translation:
    auto_generate: true

I removed all label keys from my form type files. When I load the page I see the keys being loaded:
form.formname.children.fieldname.label

But, these keys do not show up in the translation files. Now do I get them to generate? I did run the translation:update command as well, just to be sure.

Regards

**Comment by benji07** [comment]
Our bundle only generate the translation key, but not the files, because we can define multiple translations files. You need to add them manually
