### ISSUE TITLE
JmsTranslationBundle compatibility

### ISSUE THREAD

**Issue by paulandrieux** [Elao/ElaoFormTranslationBundle#5]
Hello,

Your bundle is awesome, but I cannot use it because it is not compatible with JmsTranslationBundle extraction process. I know that Jms provides a way to define our own extraction services, so I wonder if you are able to write one.

**Comment by jmeyo** [comment]
Hey, 
Did you add that feature ? doesn't look like yet. 
Anyway, if we can't extract with jmstranslation bundle, what is your recommendation to create translations entries in catalogs ?
Thx

**Comment by pimolo** [comment]
:+1:

**Comment by Padam87** [comment]
:+1:

**Comment by Tom32i** [comment]
Sorry for the delay guys, I'll try and look into it.

The main obstacle to overcome is that key here are generated dynamically here.

Can anyone give me a link to documentation and/or article about how to work with JMSTranslation extraction process?

**Comment by Tom32i** [comment]
Ok, it looks like the `JMS\TranslationBundle\Translation\ExtractorInterface` is what we need.
I'm gonna try something with it :)

**Comment by Padam87** [comment]
https://github.com/Elao/ElaoFormTranslationBundle/pull/24

**Comment by benji07** [comment]
Spring cleaning, If this issue is still relevant, please reopen-it.
